// Wechaty Puppet Service 精简 gRPC 定义
// 参考: https://github.com/wechaty/grpc/blob/master/proto/wechaty/puppet.proto

// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.6.1
// - protoc             v6.33.4
// source: internal/channel/wechat/wechaty/proto/puppet.proto

package proto

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	Puppet_Start_FullMethodName           = "/wechaty.Puppet/Start"
	Puppet_Stop_FullMethodName            = "/wechaty.Puppet/Stop"
	Puppet_Logout_FullMethodName          = "/wechaty.Puppet/Logout"
	Puppet_Event_FullMethodName           = "/wechaty.Puppet/Event"
	Puppet_MessageSendText_FullMethodName = "/wechaty.Puppet/MessageSendText"
	Puppet_MessagePayload_FullMethodName  = "/wechaty.Puppet/MessagePayload"
	Puppet_ContactPayload_FullMethodName  = "/wechaty.Puppet/ContactPayload"
	Puppet_RoomPayload_FullMethodName     = "/wechaty.Puppet/RoomPayload"
)

// PuppetClient is the client API for Puppet service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
//
// Puppet Wechaty gRPC Puppet 服务
type PuppetClient interface {
	// Start 启动 Puppet
	Start(ctx context.Context, in *StartRequest, opts ...grpc.CallOption) (*StartResponse, error)
	// Stop 停止 Puppet
	Stop(ctx context.Context, in *StopRequest, opts ...grpc.CallOption) (*StopResponse, error)
	// Logout 登出
	Logout(ctx context.Context, in *LogoutRequest, opts ...grpc.CallOption) (*LogoutResponse, error)
	// Event 事件流（服务端流式 RPC）
	Event(ctx context.Context, in *EventRequest, opts ...grpc.CallOption) (grpc.ServerStreamingClient[EventResponse], error)
	// MessageSendText 发送文本消息
	MessageSendText(ctx context.Context, in *MessageSendTextRequest, opts ...grpc.CallOption) (*MessageSendTextResponse, error)
	// MessagePayload 获取消息详情
	MessagePayload(ctx context.Context, in *MessagePayloadRequest, opts ...grpc.CallOption) (*MessagePayloadResponse, error)
	// ContactPayload 获取联系人详情
	ContactPayload(ctx context.Context, in *ContactPayloadRequest, opts ...grpc.CallOption) (*ContactPayloadResponse, error)
	// RoomPayload 获取群聊详情
	RoomPayload(ctx context.Context, in *RoomPayloadRequest, opts ...grpc.CallOption) (*RoomPayloadResponse, error)
}

type puppetClient struct {
	cc grpc.ClientConnInterface
}

func NewPuppetClient(cc grpc.ClientConnInterface) PuppetClient {
	return &puppetClient{cc}
}

func (c *puppetClient) Start(ctx context.Context, in *StartRequest, opts ...grpc.CallOption) (*StartResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(StartResponse)
	err := c.cc.Invoke(ctx, Puppet_Start_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *puppetClient) Stop(ctx context.Context, in *StopRequest, opts ...grpc.CallOption) (*StopResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(StopResponse)
	err := c.cc.Invoke(ctx, Puppet_Stop_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *puppetClient) Logout(ctx context.Context, in *LogoutRequest, opts ...grpc.CallOption) (*LogoutResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(LogoutResponse)
	err := c.cc.Invoke(ctx, Puppet_Logout_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *puppetClient) Event(ctx context.Context, in *EventRequest, opts ...grpc.CallOption) (grpc.ServerStreamingClient[EventResponse], error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	stream, err := c.cc.NewStream(ctx, &Puppet_ServiceDesc.Streams[0], Puppet_Event_FullMethodName, cOpts...)
	if err != nil {
		return nil, err
	}
	x := &grpc.GenericClientStream[EventRequest, EventResponse]{ClientStream: stream}
	if err := x.ClientStream.SendMsg(in); err != nil {
		return nil, err
	}
	if err := x.ClientStream.CloseSend(); err != nil {
		return nil, err
	}
	return x, nil
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type Puppet_EventClient = grpc.ServerStreamingClient[EventResponse]

func (c *puppetClient) MessageSendText(ctx context.Context, in *MessageSendTextRequest, opts ...grpc.CallOption) (*MessageSendTextResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(MessageSendTextResponse)
	err := c.cc.Invoke(ctx, Puppet_MessageSendText_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *puppetClient) MessagePayload(ctx context.Context, in *MessagePayloadRequest, opts ...grpc.CallOption) (*MessagePayloadResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(MessagePayloadResponse)
	err := c.cc.Invoke(ctx, Puppet_MessagePayload_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *puppetClient) ContactPayload(ctx context.Context, in *ContactPayloadRequest, opts ...grpc.CallOption) (*ContactPayloadResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ContactPayloadResponse)
	err := c.cc.Invoke(ctx, Puppet_ContactPayload_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *puppetClient) RoomPayload(ctx context.Context, in *RoomPayloadRequest, opts ...grpc.CallOption) (*RoomPayloadResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(RoomPayloadResponse)
	err := c.cc.Invoke(ctx, Puppet_RoomPayload_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// PuppetServer is the server API for Puppet service.
// All implementations must embed UnimplementedPuppetServer
// for forward compatibility.
//
// Puppet Wechaty gRPC Puppet 服务
type PuppetServer interface {
	// Start 启动 Puppet
	Start(context.Context, *StartRequest) (*StartResponse, error)
	// Stop 停止 Puppet
	Stop(context.Context, *StopRequest) (*StopResponse, error)
	// Logout 登出
	Logout(context.Context, *LogoutRequest) (*LogoutResponse, error)
	// Event 事件流（服务端流式 RPC）
	Event(*EventRequest, grpc.ServerStreamingServer[EventResponse]) error
	// MessageSendText 发送文本消息
	MessageSendText(context.Context, *MessageSendTextRequest) (*MessageSendTextResponse, error)
	// MessagePayload 获取消息详情
	MessagePayload(context.Context, *MessagePayloadRequest) (*MessagePayloadResponse, error)
	// ContactPayload 获取联系人详情
	ContactPayload(context.Context, *ContactPayloadRequest) (*ContactPayloadResponse, error)
	// RoomPayload 获取群聊详情
	RoomPayload(context.Context, *RoomPayloadRequest) (*RoomPayloadResponse, error)
	mustEmbedUnimplementedPuppetServer()
}

// UnimplementedPuppetServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedPuppetServer struct{}

func (UnimplementedPuppetServer) Start(context.Context, *StartRequest) (*StartResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method Start not implemented")
}
func (UnimplementedPuppetServer) Stop(context.Context, *StopRequest) (*StopResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method Stop not implemented")
}
func (UnimplementedPuppetServer) Logout(context.Context, *LogoutRequest) (*LogoutResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method Logout not implemented")
}
func (UnimplementedPuppetServer) Event(*EventRequest, grpc.ServerStreamingServer[EventResponse]) error {
	return status.Error(codes.Unimplemented, "method Event not implemented")
}
func (UnimplementedPuppetServer) MessageSendText(context.Context, *MessageSendTextRequest) (*MessageSendTextResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method MessageSendText not implemented")
}
func (UnimplementedPuppetServer) MessagePayload(context.Context, *MessagePayloadRequest) (*MessagePayloadResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method MessagePayload not implemented")
}
func (UnimplementedPuppetServer) ContactPayload(context.Context, *ContactPayloadRequest) (*ContactPayloadResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method ContactPayload not implemented")
}
func (UnimplementedPuppetServer) RoomPayload(context.Context, *RoomPayloadRequest) (*RoomPayloadResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method RoomPayload not implemented")
}
func (UnimplementedPuppetServer) mustEmbedUnimplementedPuppetServer() {}
func (UnimplementedPuppetServer) testEmbeddedByValue()                {}

// UnsafePuppetServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to PuppetServer will
// result in compilation errors.
type UnsafePuppetServer interface {
	mustEmbedUnimplementedPuppetServer()
}

func RegisterPuppetServer(s grpc.ServiceRegistrar, srv PuppetServer) {
	// If the following call panics, it indicates UnimplementedPuppetServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&Puppet_ServiceDesc, srv)
}

func _Puppet_Start_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(StartRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(PuppetServer).Start(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Puppet_Start_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(PuppetServer).Start(ctx, req.(*StartRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Puppet_Stop_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(StopRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(PuppetServer).Stop(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Puppet_Stop_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(PuppetServer).Stop(ctx, req.(*StopRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Puppet_Logout_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(LogoutRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(PuppetServer).Logout(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Puppet_Logout_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(PuppetServer).Logout(ctx, req.(*LogoutRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Puppet_Event_Handler(srv interface{}, stream grpc.ServerStream) error {
	m := new(EventRequest)
	if err := stream.RecvMsg(m); err != nil {
		return err
	}
	return srv.(PuppetServer).Event(m, &grpc.GenericServerStream[EventRequest, EventResponse]{ServerStream: stream})
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type Puppet_EventServer = grpc.ServerStreamingServer[EventResponse]

func _Puppet_MessageSendText_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(MessageSendTextRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(PuppetServer).MessageSendText(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Puppet_MessageSendText_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(PuppetServer).MessageSendText(ctx, req.(*MessageSendTextRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Puppet_MessagePayload_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(MessagePayloadRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(PuppetServer).MessagePayload(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Puppet_MessagePayload_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(PuppetServer).MessagePayload(ctx, req.(*MessagePayloadRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Puppet_ContactPayload_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ContactPayloadRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(PuppetServer).ContactPayload(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Puppet_ContactPayload_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(PuppetServer).ContactPayload(ctx, req.(*ContactPayloadRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Puppet_RoomPayload_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(RoomPayloadRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(PuppetServer).RoomPayload(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Puppet_RoomPayload_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(PuppetServer).RoomPayload(ctx, req.(*RoomPayloadRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// Puppet_ServiceDesc is the grpc.ServiceDesc for Puppet service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var Puppet_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "wechaty.Puppet",
	HandlerType: (*PuppetServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "Start",
			Handler:    _Puppet_Start_Handler,
		},
		{
			MethodName: "Stop",
			Handler:    _Puppet_Stop_Handler,
		},
		{
			MethodName: "Logout",
			Handler:    _Puppet_Logout_Handler,
		},
		{
			MethodName: "MessageSendText",
			Handler:    _Puppet_MessageSendText_Handler,
		},
		{
			MethodName: "MessagePayload",
			Handler:    _Puppet_MessagePayload_Handler,
		},
		{
			MethodName: "ContactPayload",
			Handler:    _Puppet_ContactPayload_Handler,
		},
		{
			MethodName: "RoomPayload",
			Handler:    _Puppet_RoomPayload_Handler,
		},
	},
	Streams: []grpc.StreamDesc{
		{
			StreamName:    "Event",
			Handler:       _Puppet_Event_Handler,
			ServerStreams: true,
		},
	},
	Metadata: "internal/channel/wechat/wechaty/proto/puppet.proto",
}
