// Wechaty Puppet Service 精简 gRPC 定义
// 参考: https://github.com/wechaty/grpc/blob/master/proto/wechaty/puppet.proto

// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v6.33.4
// source: internal/channel/wechat/wechaty/proto/puppet.proto

package proto

import (
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"

	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// EventType 事件类型
type EventType int32

const (
	EventType_EVENT_TYPE_UNSPECIFIED EventType = 0
	EventType_EVENT_TYPE_HEARTBEAT   EventType = 1
	EventType_EVENT_TYPE_LOGIN       EventType = 2
	EventType_EVENT_TYPE_LOGOUT      EventType = 3
	EventType_EVENT_TYPE_MESSAGE     EventType = 4
	EventType_EVENT_TYPE_SCAN        EventType = 5
	EventType_EVENT_TYPE_DONG        EventType = 6
	EventType_EVENT_TYPE_ERROR       EventType = 7
	EventType_EVENT_TYPE_FRIENDSHIP  EventType = 8
	EventType_EVENT_TYPE_ROOM_INVITE EventType = 9
	EventType_EVENT_TYPE_ROOM_JOIN   EventType = 10
	EventType_EVENT_TYPE_ROOM_LEAVE  EventType = 11
	EventType_EVENT_TYPE_ROOM_TOPIC  EventType = 12
	EventType_EVENT_TYPE_READY       EventType = 13
	EventType_EVENT_TYPE_RESET       EventType = 14
)

// Enum value maps for EventType.
var (
	EventType_name = map[int32]string{
		0:  "EVENT_TYPE_UNSPECIFIED",
		1:  "EVENT_TYPE_HEARTBEAT",
		2:  "EVENT_TYPE_LOGIN",
		3:  "EVENT_TYPE_LOGOUT",
		4:  "EVENT_TYPE_MESSAGE",
		5:  "EVENT_TYPE_SCAN",
		6:  "EVENT_TYPE_DONG",
		7:  "EVENT_TYPE_ERROR",
		8:  "EVENT_TYPE_FRIENDSHIP",
		9:  "EVENT_TYPE_ROOM_INVITE",
		10: "EVENT_TYPE_ROOM_JOIN",
		11: "EVENT_TYPE_ROOM_LEAVE",
		12: "EVENT_TYPE_ROOM_TOPIC",
		13: "EVENT_TYPE_READY",
		14: "EVENT_TYPE_RESET",
	}
	EventType_value = map[string]int32{
		"EVENT_TYPE_UNSPECIFIED": 0,
		"EVENT_TYPE_HEARTBEAT":   1,
		"EVENT_TYPE_LOGIN":       2,
		"EVENT_TYPE_LOGOUT":      3,
		"EVENT_TYPE_MESSAGE":     4,
		"EVENT_TYPE_SCAN":        5,
		"EVENT_TYPE_DONG":        6,
		"EVENT_TYPE_ERROR":       7,
		"EVENT_TYPE_FRIENDSHIP":  8,
		"EVENT_TYPE_ROOM_INVITE": 9,
		"EVENT_TYPE_ROOM_JOIN":   10,
		"EVENT_TYPE_ROOM_LEAVE":  11,
		"EVENT_TYPE_ROOM_TOPIC":  12,
		"EVENT_TYPE_READY":       13,
		"EVENT_TYPE_RESET":       14,
	}
)

func (x EventType) Enum() *EventType {
	p := new(EventType)
	*p = x
	return p
}

func (x EventType) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (EventType) Descriptor() protoreflect.EnumDescriptor {
	return file_internal_channel_wechat_wechaty_proto_puppet_proto_enumTypes[0].Descriptor()
}

func (EventType) Type() protoreflect.EnumType {
	return &file_internal_channel_wechat_wechaty_proto_puppet_proto_enumTypes[0]
}

func (x EventType) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use EventType.Descriptor instead.
func (EventType) EnumDescriptor() ([]byte, []int) {
	return file_internal_channel_wechat_wechaty_proto_puppet_proto_rawDescGZIP(), []int{0}
}

// MessageType 消息类型
type MessageType int32

const (
	MessageType_MESSAGE_TYPE_UNSPECIFIED  MessageType = 0
	MessageType_MESSAGE_TYPE_ATTACHMENT   MessageType = 1
	MessageType_MESSAGE_TYPE_AUDIO        MessageType = 2
	MessageType_MESSAGE_TYPE_CONTACT      MessageType = 3
	MessageType_MESSAGE_TYPE_CHATHISTORY  MessageType = 4
	MessageType_MESSAGE_TYPE_EMOTICON     MessageType = 5
	MessageType_MESSAGE_TYPE_IMAGE        MessageType = 6
	MessageType_MESSAGE_TYPE_TEXT         MessageType = 7
	MessageType_MESSAGE_TYPE_LOCATION     MessageType = 8
	MessageType_MESSAGE_TYPE_MINI_PROGRAM MessageType = 9
	MessageType_MESSAGE_TYPE_TRANSFER     MessageType = 10
	MessageType_MESSAGE_TYPE_RED_ENVELOPE MessageType = 11
	MessageType_MESSAGE_TYPE_RECALLED     MessageType = 12
	MessageType_MESSAGE_TYPE_URL          MessageType = 13
	MessageType_MESSAGE_TYPE_VIDEO        MessageType = 14
)

// Enum value maps for MessageType.
var (
	MessageType_name = map[int32]string{
		0:  "MESSAGE_TYPE_UNSPECIFIED",
		1:  "MESSAGE_TYPE_ATTACHMENT",
		2:  "MESSAGE_TYPE_AUDIO",
		3:  "MESSAGE_TYPE_CONTACT",
		4:  "MESSAGE_TYPE_CHATHISTORY",
		5:  "MESSAGE_TYPE_EMOTICON",
		6:  "MESSAGE_TYPE_IMAGE",
		7:  "MESSAGE_TYPE_TEXT",
		8:  "MESSAGE_TYPE_LOCATION",
		9:  "MESSAGE_TYPE_MINI_PROGRAM",
		10: "MESSAGE_TYPE_TRANSFER",
		11: "MESSAGE_TYPE_RED_ENVELOPE",
		12: "MESSAGE_TYPE_RECALLED",
		13: "MESSAGE_TYPE_URL",
		14: "MESSAGE_TYPE_VIDEO",
	}
	MessageType_value = map[string]int32{
		"MESSAGE_TYPE_UNSPECIFIED":  0,
		"MESSAGE_TYPE_ATTACHMENT":   1,
		"MESSAGE_TYPE_AUDIO":        2,
		"MESSAGE_TYPE_CONTACT":      3,
		"MESSAGE_TYPE_CHATHISTORY":  4,
		"MESSAGE_TYPE_EMOTICON":     5,
		"MESSAGE_TYPE_IMAGE":        6,
		"MESSAGE_TYPE_TEXT":         7,
		"MESSAGE_TYPE_LOCATION":     8,
		"MESSAGE_TYPE_MINI_PROGRAM": 9,
		"MESSAGE_TYPE_TRANSFER":     10,
		"MESSAGE_TYPE_RED_ENVELOPE": 11,
		"MESSAGE_TYPE_RECALLED":     12,
		"MESSAGE_TYPE_URL":          13,
		"MESSAGE_TYPE_VIDEO":        14,
	}
)

func (x MessageType) Enum() *MessageType {
	p := new(MessageType)
	*p = x
	return p
}

func (x MessageType) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (MessageType) Descriptor() protoreflect.EnumDescriptor {
	return file_internal_channel_wechat_wechaty_proto_puppet_proto_enumTypes[1].Descriptor()
}

func (MessageType) Type() protoreflect.EnumType {
	return &file_internal_channel_wechat_wechaty_proto_puppet_proto_enumTypes[1]
}

func (x MessageType) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use MessageType.Descriptor instead.
func (MessageType) EnumDescriptor() ([]byte, []int) {
	return file_internal_channel_wechat_wechaty_proto_puppet_proto_rawDescGZIP(), []int{1}
}

// Start/Stop
type StartRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *StartRequest) Reset() {
	*x = StartRequest{}
	mi := &file_internal_channel_wechat_wechaty_proto_puppet_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *StartRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StartRequest) ProtoMessage() {}

func (x *StartRequest) ProtoReflect() protoreflect.Message {
	mi := &file_internal_channel_wechat_wechaty_proto_puppet_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use StartRequest.ProtoReflect.Descriptor instead.
func (*StartRequest) Descriptor() ([]byte, []int) {
	return file_internal_channel_wechat_wechaty_proto_puppet_proto_rawDescGZIP(), []int{0}
}

type StartResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *StartResponse) Reset() {
	*x = StartResponse{}
	mi := &file_internal_channel_wechat_wechaty_proto_puppet_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *StartResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StartResponse) ProtoMessage() {}

func (x *StartResponse) ProtoReflect() protoreflect.Message {
	mi := &file_internal_channel_wechat_wechaty_proto_puppet_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use StartResponse.ProtoReflect.Descriptor instead.
func (*StartResponse) Descriptor() ([]byte, []int) {
	return file_internal_channel_wechat_wechaty_proto_puppet_proto_rawDescGZIP(), []int{1}
}

type StopRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *StopRequest) Reset() {
	*x = StopRequest{}
	mi := &file_internal_channel_wechat_wechaty_proto_puppet_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *StopRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StopRequest) ProtoMessage() {}

func (x *StopRequest) ProtoReflect() protoreflect.Message {
	mi := &file_internal_channel_wechat_wechaty_proto_puppet_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use StopRequest.ProtoReflect.Descriptor instead.
func (*StopRequest) Descriptor() ([]byte, []int) {
	return file_internal_channel_wechat_wechaty_proto_puppet_proto_rawDescGZIP(), []int{2}
}

type StopResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *StopResponse) Reset() {
	*x = StopResponse{}
	mi := &file_internal_channel_wechat_wechaty_proto_puppet_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *StopResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StopResponse) ProtoMessage() {}

func (x *StopResponse) ProtoReflect() protoreflect.Message {
	mi := &file_internal_channel_wechat_wechaty_proto_puppet_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use StopResponse.ProtoReflect.Descriptor instead.
func (*StopResponse) Descriptor() ([]byte, []int) {
	return file_internal_channel_wechat_wechaty_proto_puppet_proto_rawDescGZIP(), []int{3}
}

// Logout
type LogoutRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *LogoutRequest) Reset() {
	*x = LogoutRequest{}
	mi := &file_internal_channel_wechat_wechaty_proto_puppet_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *LogoutRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*LogoutRequest) ProtoMessage() {}

func (x *LogoutRequest) ProtoReflect() protoreflect.Message {
	mi := &file_internal_channel_wechat_wechaty_proto_puppet_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use LogoutRequest.ProtoReflect.Descriptor instead.
func (*LogoutRequest) Descriptor() ([]byte, []int) {
	return file_internal_channel_wechat_wechaty_proto_puppet_proto_rawDescGZIP(), []int{4}
}

type LogoutResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *LogoutResponse) Reset() {
	*x = LogoutResponse{}
	mi := &file_internal_channel_wechat_wechaty_proto_puppet_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *LogoutResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*LogoutResponse) ProtoMessage() {}

func (x *LogoutResponse) ProtoReflect() protoreflect.Message {
	mi := &file_internal_channel_wechat_wechaty_proto_puppet_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use LogoutResponse.ProtoReflect.Descriptor instead.
func (*LogoutResponse) Descriptor() ([]byte, []int) {
	return file_internal_channel_wechat_wechaty_proto_puppet_proto_rawDescGZIP(), []int{5}
}

// Event
type EventRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *EventRequest) Reset() {
	*x = EventRequest{}
	mi := &file_internal_channel_wechat_wechaty_proto_puppet_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *EventRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*EventRequest) ProtoMessage() {}

func (x *EventRequest) ProtoReflect() protoreflect.Message {
	mi := &file_internal_channel_wechat_wechaty_proto_puppet_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use EventRequest.ProtoReflect.Descriptor instead.
func (*EventRequest) Descriptor() ([]byte, []int) {
	return file_internal_channel_wechat_wechaty_proto_puppet_proto_rawDescGZIP(), []int{6}
}

type EventResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Type          EventType              `protobuf:"varint,1,opt,name=type,proto3,enum=wechaty.EventType" json:"type,omitempty"`
	Payload       string                 `protobuf:"bytes,2,opt,name=payload,proto3" json:"payload,omitempty"` // JSON 编码的事件数据
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *EventResponse) Reset() {
	*x = EventResponse{}
	mi := &file_internal_channel_wechat_wechaty_proto_puppet_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *EventResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*EventResponse) ProtoMessage() {}

func (x *EventResponse) ProtoReflect() protoreflect.Message {
	mi := &file_internal_channel_wechat_wechaty_proto_puppet_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use EventResponse.ProtoReflect.Descriptor instead.
func (*EventResponse) Descriptor() ([]byte, []int) {
	return file_internal_channel_wechat_wechaty_proto_puppet_proto_rawDescGZIP(), []int{7}
}

func (x *EventResponse) GetType() EventType {
	if x != nil {
		return x.Type
	}
	return EventType_EVENT_TYPE_UNSPECIFIED
}

func (x *EventResponse) GetPayload() string {
	if x != nil {
		return x.Payload
	}
	return ""
}

// MessageSendText
type MessageSendTextRequest struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	ConversationId string                 `protobuf:"bytes,1,opt,name=conversation_id,json=conversationId,proto3" json:"conversation_id,omitempty"`
	Text           string                 `protobuf:"bytes,2,opt,name=text,proto3" json:"text,omitempty"`
	MentionIdList  []string               `protobuf:"bytes,3,rep,name=mention_id_list,json=mentionIdList,proto3" json:"mention_id_list,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *MessageSendTextRequest) Reset() {
	*x = MessageSendTextRequest{}
	mi := &file_internal_channel_wechat_wechaty_proto_puppet_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *MessageSendTextRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MessageSendTextRequest) ProtoMessage() {}

func (x *MessageSendTextRequest) ProtoReflect() protoreflect.Message {
	mi := &file_internal_channel_wechat_wechaty_proto_puppet_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MessageSendTextRequest.ProtoReflect.Descriptor instead.
func (*MessageSendTextRequest) Descriptor() ([]byte, []int) {
	return file_internal_channel_wechat_wechaty_proto_puppet_proto_rawDescGZIP(), []int{8}
}

func (x *MessageSendTextRequest) GetConversationId() string {
	if x != nil {
		return x.ConversationId
	}
	return ""
}

func (x *MessageSendTextRequest) GetText() string {
	if x != nil {
		return x.Text
	}
	return ""
}

func (x *MessageSendTextRequest) GetMentionIdList() []string {
	if x != nil {
		return x.MentionIdList
	}
	return nil
}

type MessageSendTextResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"` // 消息 ID（可选）
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *MessageSendTextResponse) Reset() {
	*x = MessageSendTextResponse{}
	mi := &file_internal_channel_wechat_wechaty_proto_puppet_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *MessageSendTextResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MessageSendTextResponse) ProtoMessage() {}

func (x *MessageSendTextResponse) ProtoReflect() protoreflect.Message {
	mi := &file_internal_channel_wechat_wechaty_proto_puppet_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MessageSendTextResponse.ProtoReflect.Descriptor instead.
func (*MessageSendTextResponse) Descriptor() ([]byte, []int) {
	return file_internal_channel_wechat_wechaty_proto_puppet_proto_rawDescGZIP(), []int{9}
}

func (x *MessageSendTextResponse) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

// MessagePayload
type MessagePayloadRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *MessagePayloadRequest) Reset() {
	*x = MessagePayloadRequest{}
	mi := &file_internal_channel_wechat_wechaty_proto_puppet_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *MessagePayloadRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MessagePayloadRequest) ProtoMessage() {}

func (x *MessagePayloadRequest) ProtoReflect() protoreflect.Message {
	mi := &file_internal_channel_wechat_wechaty_proto_puppet_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MessagePayloadRequest.ProtoReflect.Descriptor instead.
func (*MessagePayloadRequest) Descriptor() ([]byte, []int) {
	return file_internal_channel_wechat_wechaty_proto_puppet_proto_rawDescGZIP(), []int{10}
}

func (x *MessagePayloadRequest) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

type MessagePayloadResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	ContactId     string                 `protobuf:"bytes,2,opt,name=contact_id,json=contactId,proto3" json:"contact_id,omitempty"` // 发送者 ID
	RoomId        string                 `protobuf:"bytes,3,opt,name=room_id,json=roomId,proto3" json:"room_id,omitempty"`          // 群聊 ID（私聊为空）
	Type          MessageType            `protobuf:"varint,4,opt,name=type,proto3,enum=wechaty.MessageType" json:"type,omitempty"`
	Text          string                 `protobuf:"bytes,5,opt,name=text,proto3" json:"text,omitempty"`
	Timestamp     uint64                 `protobuf:"varint,6,opt,name=timestamp,proto3" json:"timestamp,omitempty"`
	Filename      string                 `protobuf:"bytes,7,opt,name=filename,proto3" json:"filename,omitempty"`
	MentionIdList []string               `protobuf:"bytes,8,rep,name=mention_id_list,json=mentionIdList,proto3" json:"mention_id_list,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *MessagePayloadResponse) Reset() {
	*x = MessagePayloadResponse{}
	mi := &file_internal_channel_wechat_wechaty_proto_puppet_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *MessagePayloadResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MessagePayloadResponse) ProtoMessage() {}

func (x *MessagePayloadResponse) ProtoReflect() protoreflect.Message {
	mi := &file_internal_channel_wechat_wechaty_proto_puppet_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MessagePayloadResponse.ProtoReflect.Descriptor instead.
func (*MessagePayloadResponse) Descriptor() ([]byte, []int) {
	return file_internal_channel_wechat_wechaty_proto_puppet_proto_rawDescGZIP(), []int{11}
}

func (x *MessagePayloadResponse) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *MessagePayloadResponse) GetContactId() string {
	if x != nil {
		return x.ContactId
	}
	return ""
}

func (x *MessagePayloadResponse) GetRoomId() string {
	if x != nil {
		return x.RoomId
	}
	return ""
}

func (x *MessagePayloadResponse) GetType() MessageType {
	if x != nil {
		return x.Type
	}
	return MessageType_MESSAGE_TYPE_UNSPECIFIED
}

func (x *MessagePayloadResponse) GetText() string {
	if x != nil {
		return x.Text
	}
	return ""
}

func (x *MessagePayloadResponse) GetTimestamp() uint64 {
	if x != nil {
		return x.Timestamp
	}
	return 0
}

func (x *MessagePayloadResponse) GetFilename() string {
	if x != nil {
		return x.Filename
	}
	return ""
}

func (x *MessagePayloadResponse) GetMentionIdList() []string {
	if x != nil {
		return x.MentionIdList
	}
	return nil
}

// ContactPayload
type ContactPayloadRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ContactPayloadRequest) Reset() {
	*x = ContactPayloadRequest{}
	mi := &file_internal_channel_wechat_wechaty_proto_puppet_proto_msgTypes[12]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ContactPayloadRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ContactPayloadRequest) ProtoMessage() {}

func (x *ContactPayloadRequest) ProtoReflect() protoreflect.Message {
	mi := &file_internal_channel_wechat_wechaty_proto_puppet_proto_msgTypes[12]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ContactPayloadRequest.ProtoReflect.Descriptor instead.
func (*ContactPayloadRequest) Descriptor() ([]byte, []int) {
	return file_internal_channel_wechat_wechaty_proto_puppet_proto_rawDescGZIP(), []int{12}
}

func (x *ContactPayloadRequest) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

type ContactPayloadResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Name          string                 `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	Alias         string                 `protobuf:"bytes,3,opt,name=alias,proto3" json:"alias,omitempty"`
	Avatar        string                 `protobuf:"bytes,4,opt,name=avatar,proto3" json:"avatar,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ContactPayloadResponse) Reset() {
	*x = ContactPayloadResponse{}
	mi := &file_internal_channel_wechat_wechaty_proto_puppet_proto_msgTypes[13]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ContactPayloadResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ContactPayloadResponse) ProtoMessage() {}

func (x *ContactPayloadResponse) ProtoReflect() protoreflect.Message {
	mi := &file_internal_channel_wechat_wechaty_proto_puppet_proto_msgTypes[13]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ContactPayloadResponse.ProtoReflect.Descriptor instead.
func (*ContactPayloadResponse) Descriptor() ([]byte, []int) {
	return file_internal_channel_wechat_wechaty_proto_puppet_proto_rawDescGZIP(), []int{13}
}

func (x *ContactPayloadResponse) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *ContactPayloadResponse) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *ContactPayloadResponse) GetAlias() string {
	if x != nil {
		return x.Alias
	}
	return ""
}

func (x *ContactPayloadResponse) GetAvatar() string {
	if x != nil {
		return x.Avatar
	}
	return ""
}

// RoomPayload
type RoomPayloadRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RoomPayloadRequest) Reset() {
	*x = RoomPayloadRequest{}
	mi := &file_internal_channel_wechat_wechaty_proto_puppet_proto_msgTypes[14]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RoomPayloadRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RoomPayloadRequest) ProtoMessage() {}

func (x *RoomPayloadRequest) ProtoReflect() protoreflect.Message {
	mi := &file_internal_channel_wechat_wechaty_proto_puppet_proto_msgTypes[14]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RoomPayloadRequest.ProtoReflect.Descriptor instead.
func (*RoomPayloadRequest) Descriptor() ([]byte, []int) {
	return file_internal_channel_wechat_wechaty_proto_puppet_proto_rawDescGZIP(), []int{14}
}

func (x *RoomPayloadRequest) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

type RoomPayloadResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Topic         string                 `protobuf:"bytes,2,opt,name=topic,proto3" json:"topic,omitempty"`
	MemberIdList  []string               `protobuf:"bytes,3,rep,name=member_id_list,json=memberIdList,proto3" json:"member_id_list,omitempty"`
	OwnerId       string                 `protobuf:"bytes,4,opt,name=owner_id,json=ownerId,proto3" json:"owner_id,omitempty"`
	Avatar        string                 `protobuf:"bytes,5,opt,name=avatar,proto3" json:"avatar,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RoomPayloadResponse) Reset() {
	*x = RoomPayloadResponse{}
	mi := &file_internal_channel_wechat_wechaty_proto_puppet_proto_msgTypes[15]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RoomPayloadResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RoomPayloadResponse) ProtoMessage() {}

func (x *RoomPayloadResponse) ProtoReflect() protoreflect.Message {
	mi := &file_internal_channel_wechat_wechaty_proto_puppet_proto_msgTypes[15]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RoomPayloadResponse.ProtoReflect.Descriptor instead.
func (*RoomPayloadResponse) Descriptor() ([]byte, []int) {
	return file_internal_channel_wechat_wechaty_proto_puppet_proto_rawDescGZIP(), []int{15}
}

func (x *RoomPayloadResponse) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *RoomPayloadResponse) GetTopic() string {
	if x != nil {
		return x.Topic
	}
	return ""
}

func (x *RoomPayloadResponse) GetMemberIdList() []string {
	if x != nil {
		return x.MemberIdList
	}
	return nil
}

func (x *RoomPayloadResponse) GetOwnerId() string {
	if x != nil {
		return x.OwnerId
	}
	return ""
}

func (x *RoomPayloadResponse) GetAvatar() string {
	if x != nil {
		return x.Avatar
	}
	return ""
}

var File_internal_channel_wechat_wechaty_proto_puppet_proto protoreflect.FileDescriptor

const file_internal_channel_wechat_wechaty_proto_puppet_proto_rawDesc = "" +
	"\n" +
	"2internal/channel/wechat/wechaty/proto/puppet.proto\x12\awechaty\"\x0e\n" +
	"\fStartRequest\"\x0f\n" +
	"\rStartResponse\"\r\n" +
	"\vStopRequest\"\x0e\n" +
	"\fStopResponse\"\x0f\n" +
	"\rLogoutRequest\"\x10\n" +
	"\x0eLogoutResponse\"\x0e\n" +
	"\fEventRequest\"Q\n" +
	"\rEventResponse\x12&\n" +
	"\x04type\x18\x01 \x01(\x0e2\x12.wechaty.EventTypeR\x04type\x12\x18\n" +
	"\apayload\x18\x02 \x01(\tR\apayload\"}\n" +
	"\x16MessageSendTextRequest\x12'\n" +
	"\x0fconversation_id\x18\x01 \x01(\tR\x0econversationId\x12\x12\n" +
	"\x04text\x18\x02 \x01(\tR\x04text\x12&\n" +
	"\x0fmention_id_list\x18\x03 \x03(\tR\rmentionIdList\")\n" +
	"\x17MessageSendTextResponse\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\"'\n" +
	"\x15MessagePayloadRequest\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\"\x80\x02\n" +
	"\x16MessagePayloadResponse\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x1d\n" +
	"\n" +
	"contact_id\x18\x02 \x01(\tR\tcontactId\x12\x17\n" +
	"\aroom_id\x18\x03 \x01(\tR\x06roomId\x12(\n" +
	"\x04type\x18\x04 \x01(\x0e2\x14.wechaty.MessageTypeR\x04type\x12\x12\n" +
	"\x04text\x18\x05 \x01(\tR\x04text\x12\x1c\n" +
	"\ttimestamp\x18\x06 \x01(\x04R\ttimestamp\x12\x1a\n" +
	"\bfilename\x18\a \x01(\tR\bfilename\x12&\n" +
	"\x0fmention_id_list\x18\b \x03(\tR\rmentionIdList\"'\n" +
	"\x15ContactPayloadRequest\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\"j\n" +
	"\x16ContactPayloadResponse\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x12\n" +
	"\x04name\x18\x02 \x01(\tR\x04name\x12\x14\n" +
	"\x05alias\x18\x03 \x01(\tR\x05alias\x12\x16\n" +
	"\x06avatar\x18\x04 \x01(\tR\x06avatar\"$\n" +
	"\x12RoomPayloadRequest\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\"\x94\x01\n" +
	"\x13RoomPayloadResponse\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x14\n" +
	"\x05topic\x18\x02 \x01(\tR\x05topic\x12$\n" +
	"\x0emember_id_list\x18\x03 \x03(\tR\fmemberIdList\x12\x19\n" +
	"\bowner_id\x18\x04 \x01(\tR\aownerId\x12\x16\n" +
	"\x06avatar\x18\x05 \x01(\tR\x06avatar*\xf9\x02\n" +
	"\tEventType\x12\x1a\n" +
	"\x16EVENT_TYPE_UNSPECIFIED\x10\x00\x12\x18\n" +
	"\x14EVENT_TYPE_HEARTBEAT\x10\x01\x12\x14\n" +
	"\x10EVENT_TYPE_LOGIN\x10\x02\x12\x15\n" +
	"\x11EVENT_TYPE_LOGOUT\x10\x03\x12\x16\n" +
	"\x12EVENT_TYPE_MESSAGE\x10\x04\x12\x13\n" +
	"\x0fEVENT_TYPE_SCAN\x10\x05\x12\x13\n" +
	"\x0fEVENT_TYPE_DONG\x10\x06\x12\x14\n" +
	"\x10EVENT_TYPE_ERROR\x10\a\x12\x19\n" +
	"\x15EVENT_TYPE_FRIENDSHIP\x10\b\x12\x1a\n" +
	"\x16EVENT_TYPE_ROOM_INVITE\x10\t\x12\x18\n" +
	"\x14EVENT_TYPE_ROOM_JOIN\x10\n" +
	"\x12\x19\n" +
	"\x15EVENT_TYPE_ROOM_LEAVE\x10\v\x12\x19\n" +
	"\x15EVENT_TYPE_ROOM_TOPIC\x10\f\x12\x14\n" +
	"\x10EVENT_TYPE_READY\x10\r\x12\x14\n" +
	"\x10EVENT_TYPE_RESET\x10\x0e*\x9f\x03\n" +
	"\vMessageType\x12\x1c\n" +
	"\x18MESSAGE_TYPE_UNSPECIFIED\x10\x00\x12\x1b\n" +
	"\x17MESSAGE_TYPE_ATTACHMENT\x10\x01\x12\x16\n" +
	"\x12MESSAGE_TYPE_AUDIO\x10\x02\x12\x18\n" +
	"\x14MESSAGE_TYPE_CONTACT\x10\x03\x12\x1c\n" +
	"\x18MESSAGE_TYPE_CHATHISTORY\x10\x04\x12\x19\n" +
	"\x15MESSAGE_TYPE_EMOTICON\x10\x05\x12\x16\n" +
	"\x12MESSAGE_TYPE_IMAGE\x10\x06\x12\x15\n" +
	"\x11MESSAGE_TYPE_TEXT\x10\a\x12\x19\n" +
	"\x15MESSAGE_TYPE_LOCATION\x10\b\x12\x1d\n" +
	"\x19MESSAGE_TYPE_MINI_PROGRAM\x10\t\x12\x19\n" +
	"\x15MESSAGE_TYPE_TRANSFER\x10\n" +
	"\x12\x1d\n" +
	"\x19MESSAGE_TYPE_RED_ENVELOPE\x10\v\x12\x19\n" +
	"\x15MESSAGE_TYPE_RECALLED\x10\f\x12\x14\n" +
	"\x10MESSAGE_TYPE_URL\x10\r\x12\x16\n" +
	"\x12MESSAGE_TYPE_VIDEO\x10\x0e2\xb0\x04\n" +
	"\x06Puppet\x126\n" +
	"\x05Start\x12\x15.wechaty.StartRequest\x1a\x16.wechaty.StartResponse\x123\n" +
	"\x04Stop\x12\x14.wechaty.StopRequest\x1a\x15.wechaty.StopResponse\x129\n" +
	"\x06Logout\x12\x16.wechaty.LogoutRequest\x1a\x17.wechaty.LogoutResponse\x128\n" +
	"\x05Event\x12\x15.wechaty.EventRequest\x1a\x16.wechaty.EventResponse0\x01\x12T\n" +
	"\x0fMessageSendText\x12\x1f.wechaty.MessageSendTextRequest\x1a .wechaty.MessageSendTextResponse\x12Q\n" +
	"\x0eMessagePayload\x12\x1e.wechaty.MessagePayloadRequest\x1a\x1f.wechaty.MessagePayloadResponse\x12Q\n" +
	"\x0eContactPayload\x12\x1e.wechaty.ContactPayloadRequest\x1a\x1f.wechaty.ContactPayloadResponse\x12H\n" +
	"\vRoomPayload\x12\x1b.wechaty.RoomPayloadRequest\x1a\x1c.wechaty.RoomPayloadResponseBGZEgithub.com/chef-guo/agents-hive/internal/channel/wechat/wechaty/protob\x06proto3"

var (
	file_internal_channel_wechat_wechaty_proto_puppet_proto_rawDescOnce sync.Once
	file_internal_channel_wechat_wechaty_proto_puppet_proto_rawDescData []byte
)

func file_internal_channel_wechat_wechaty_proto_puppet_proto_rawDescGZIP() []byte {
	file_internal_channel_wechat_wechaty_proto_puppet_proto_rawDescOnce.Do(func() {
		file_internal_channel_wechat_wechaty_proto_puppet_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_internal_channel_wechat_wechaty_proto_puppet_proto_rawDesc), len(file_internal_channel_wechat_wechaty_proto_puppet_proto_rawDesc)))
	})
	return file_internal_channel_wechat_wechaty_proto_puppet_proto_rawDescData
}

var file_internal_channel_wechat_wechaty_proto_puppet_proto_enumTypes = make([]protoimpl.EnumInfo, 2)
var file_internal_channel_wechat_wechaty_proto_puppet_proto_msgTypes = make([]protoimpl.MessageInfo, 16)
var file_internal_channel_wechat_wechaty_proto_puppet_proto_goTypes = []any{
	(EventType)(0),                  // 0: wechaty.EventType
	(MessageType)(0),                // 1: wechaty.MessageType
	(*StartRequest)(nil),            // 2: wechaty.StartRequest
	(*StartResponse)(nil),           // 3: wechaty.StartResponse
	(*StopRequest)(nil),             // 4: wechaty.StopRequest
	(*StopResponse)(nil),            // 5: wechaty.StopResponse
	(*LogoutRequest)(nil),           // 6: wechaty.LogoutRequest
	(*LogoutResponse)(nil),          // 7: wechaty.LogoutResponse
	(*EventRequest)(nil),            // 8: wechaty.EventRequest
	(*EventResponse)(nil),           // 9: wechaty.EventResponse
	(*MessageSendTextRequest)(nil),  // 10: wechaty.MessageSendTextRequest
	(*MessageSendTextResponse)(nil), // 11: wechaty.MessageSendTextResponse
	(*MessagePayloadRequest)(nil),   // 12: wechaty.MessagePayloadRequest
	(*MessagePayloadResponse)(nil),  // 13: wechaty.MessagePayloadResponse
	(*ContactPayloadRequest)(nil),   // 14: wechaty.ContactPayloadRequest
	(*ContactPayloadResponse)(nil),  // 15: wechaty.ContactPayloadResponse
	(*RoomPayloadRequest)(nil),      // 16: wechaty.RoomPayloadRequest
	(*RoomPayloadResponse)(nil),     // 17: wechaty.RoomPayloadResponse
}
var file_internal_channel_wechat_wechaty_proto_puppet_proto_depIdxs = []int32{
	0,  // 0: wechaty.EventResponse.type:type_name -> wechaty.EventType
	1,  // 1: wechaty.MessagePayloadResponse.type:type_name -> wechaty.MessageType
	2,  // 2: wechaty.Puppet.Start:input_type -> wechaty.StartRequest
	4,  // 3: wechaty.Puppet.Stop:input_type -> wechaty.StopRequest
	6,  // 4: wechaty.Puppet.Logout:input_type -> wechaty.LogoutRequest
	8,  // 5: wechaty.Puppet.Event:input_type -> wechaty.EventRequest
	10, // 6: wechaty.Puppet.MessageSendText:input_type -> wechaty.MessageSendTextRequest
	12, // 7: wechaty.Puppet.MessagePayload:input_type -> wechaty.MessagePayloadRequest
	14, // 8: wechaty.Puppet.ContactPayload:input_type -> wechaty.ContactPayloadRequest
	16, // 9: wechaty.Puppet.RoomPayload:input_type -> wechaty.RoomPayloadRequest
	3,  // 10: wechaty.Puppet.Start:output_type -> wechaty.StartResponse
	5,  // 11: wechaty.Puppet.Stop:output_type -> wechaty.StopResponse
	7,  // 12: wechaty.Puppet.Logout:output_type -> wechaty.LogoutResponse
	9,  // 13: wechaty.Puppet.Event:output_type -> wechaty.EventResponse
	11, // 14: wechaty.Puppet.MessageSendText:output_type -> wechaty.MessageSendTextResponse
	13, // 15: wechaty.Puppet.MessagePayload:output_type -> wechaty.MessagePayloadResponse
	15, // 16: wechaty.Puppet.ContactPayload:output_type -> wechaty.ContactPayloadResponse
	17, // 17: wechaty.Puppet.RoomPayload:output_type -> wechaty.RoomPayloadResponse
	10, // [10:18] is the sub-list for method output_type
	2,  // [2:10] is the sub-list for method input_type
	2,  // [2:2] is the sub-list for extension type_name
	2,  // [2:2] is the sub-list for extension extendee
	0,  // [0:2] is the sub-list for field type_name
}

func init() { file_internal_channel_wechat_wechaty_proto_puppet_proto_init() }
func file_internal_channel_wechat_wechaty_proto_puppet_proto_init() {
	if File_internal_channel_wechat_wechaty_proto_puppet_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_internal_channel_wechat_wechaty_proto_puppet_proto_rawDesc), len(file_internal_channel_wechat_wechaty_proto_puppet_proto_rawDesc)),
			NumEnums:      2,
			NumMessages:   16,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_internal_channel_wechat_wechaty_proto_puppet_proto_goTypes,
		DependencyIndexes: file_internal_channel_wechat_wechaty_proto_puppet_proto_depIdxs,
		EnumInfos:         file_internal_channel_wechat_wechaty_proto_puppet_proto_enumTypes,
		MessageInfos:      file_internal_channel_wechat_wechaty_proto_puppet_proto_msgTypes,
	}.Build()
	File_internal_channel_wechat_wechaty_proto_puppet_proto = out.File
	file_internal_channel_wechat_wechaty_proto_puppet_proto_goTypes = nil
	file_internal_channel_wechat_wechaty_proto_puppet_proto_depIdxs = nil
}
