package tools

import (
	"context"
	"encoding/json"
	"fmt"
	"os"
	"strings"

	"go.uber.org/zap"

	"github.com/chef-guo/agents-hive/internal/errs"
	"github.com/chef-guo/agents-hive/internal/mcphost"
)

const (
	maxPatchSize = 1024 * 1024 // 最大 1MB
	backupSuffix = ".patch.bak"
)

type applyPatchInput struct {
	Patch   string `json:"patch"`             // unified diff 格式的补丁
	Reverse bool   `json:"reverse,omitempty"` // 是否反向应用（撤销）
	DryRun  bool   `json:"dry_run,omitempty"` // 是否只验证不应用
	Backup  *bool  `json:"backup,omitempty"`  // 是否创建备份（nil 时默认 true）
}

func registerApplyPatch(host *mcphost.Host, logger *zap.Logger) {
	schema, _ := json.Marshal(map[string]any{
		"type": "object",
		"properties": map[string]any{
			"patch": map[string]any{
				"type":        "string",
				"description": "unified diff 格式的补丁内容",
			},
			"reverse": map[string]any{
				"type":        "boolean",
				"description": "是否反向应用（撤销补丁），默认 false",
			},
			"dry_run": map[string]any{
				"type":        "boolean",
				"description": "是否只验证补丁而不实际应用，默认 false",
			},
			"backup": map[string]any{
				"type":        "boolean",
				"description": "是否创建备份文件，默认 true",
			},
		},
		"required": []string{"patch"},
	})

	host.RegisterTool(
		mcphost.ToolDefinition{
			Name:        "apply_patch",
			Description: "Apply a unified diff format patch to one or more files. Use this when you have a patch generated by git diff or a diff tool, and want to apply it programmatically. Supports multi-file patches atomically.\n\n**When to use**: Apply a unified diff patch to modify files. Ideal for applying code review suggestions, merging changes from external sources, or applying refactoring patches. Use when the edit tool is not suitable because you have a complete diff rather than knowing the exact strings to replace.\n\n**Parameters**:\n- `patch`: Unified diff format patch content. Must follow the standard unified diff format with ---/+++ headers and @@ hunk markers. Required.\n- `reverse` (optional): When true, reverses the patch (undoes the changes). Default is false.\n- `dry_run` (optional): When true, validates the patch without actually modifying any files. Useful to check if a patch will apply cleanly. Default is false.\n- `backup` (optional): When true, creates .patch.bak backup files before applying. Default is true (disabled only when dry_run or reverse is true).\n\n**Relationship to other tools**:\n- Use edit for single-file, targeted string replacements where you know the exact old and new text.\n- Use apply_patch when you have a unified diff patch or need to modify multiple files atomically.\n- apply_patch can apply hunks with fuzzy matching (context lines do not need to be exact), unlike edit which requires exact string match.\n\n**Safety constraints**:\n- Maximum patch size is 1MB to prevent memory issues.\n- Path traversal attacks (../etc/passwd) are blocked.\n- If any file in a multi-file patch fails to apply, all changes are rolled back.\n- Hunk context mismatch causes the patch application to fail (use dry_run to check first).\n\n**Output format**: Returns a summary of successfully patched files, or an error describing what failed. On failure, all changes are automatically rolled back.",
			InputSchema: schema,
		},
		func(ctx context.Context, input json.RawMessage) (*mcphost.ToolResult, error) {
			var params applyPatchInput
			if err := json.Unmarshal(input, &params); err != nil {
				return errorResult("输入无效: " + err.Error()), nil
			}

			// 设置默认值：用户未传 backup 时，非 dry-run 且非 reverse 模式下默认启用备份
			backup := true
			if params.Backup != nil {
				backup = *params.Backup
			} else if params.DryRun || params.Reverse {
				backup = false
			}

			// 检查补丁大小
			if len(params.Patch) > maxPatchSize {
				return errorResult(fmt.Sprintf("补丁过大：%d 字节，最大允许 %d 字节", len(params.Patch), maxPatchSize)), nil
			}

			// 解析补丁
			patch, err := ParsePatch(params.Patch)
			if err != nil {
				return errorResult("补丁解析失败: " + err.Error()), nil
			}

			// 应用补丁
			result, err := applyPatch(patch, params.Reverse, params.DryRun, backup, logger)
			if err != nil {
				return errorResult("应用补丁失败: " + err.Error()), nil
			}

			return textResult(result), nil
		},
	)
}

// applyPatch 应用补丁到文件
func applyPatch(patch *Patch, reverse bool, dryRun bool, backup bool, logger *zap.Logger) (string, error) {
	// 步骤 1: 验证所有文件可访问并检查路径安全性
	for _, fp := range patch.Files {
		filePath := fp.NewPath
		if reverse {
			filePath = fp.OldPath
		}

		// 路径安全检查（与 write_file/edit 等工具一致）
		if err := validatePath(filePath); err != nil {
			return "", errs.New(errs.CodeInvalidInput, fmt.Sprintf("路径安全校验失败: %s", err.Error()))
		}

		// 检查文件是否存在
		if _, err := os.Stat(filePath); err != nil {
			return "", errs.Wrap(errs.CodeStoreParseFailed, fmt.Sprintf("文件不可访问: %s", filePath), err)
		}
	}

	if dryRun {
		// Dry run 模式：只验证，不实际应用
		var results []string
		for _, fp := range patch.Files {
			filePath := fp.NewPath
			if reverse {
				filePath = fp.OldPath
			}

			if err := validateFilePatch(filePath, &fp, reverse); err != nil {
				return "", errs.Wrap(errs.CodeInvalidInput, fmt.Sprintf("验证失败 %s", filePath), err)
			}

			results = append(results, fmt.Sprintf("✓ %s 验证通过", filePath))
		}

		return fmt.Sprintf("Dry run 成功（共 %d 个文件）:\n%s", len(patch.Files), strings.Join(results, "\n")), nil
	}

	// 步骤 1.5: 获取所有涉及文件的锁（按路径排序避免死锁，仅非 dry-run）
	paths := make([]string, 0, len(patch.Files))
	for _, fp := range patch.Files {
		if reverse {
			paths = append(paths, fp.OldPath)
		} else {
			paths = append(paths, fp.NewPath)
		}
	}
	defer globalFileLock.LockFiles(paths)()

	// 步骤 2: 创建备份（如果需要）
	backups := make(map[string]string) // filePath -> backupPath
	if backup {
		for _, fp := range patch.Files {
			filePath := fp.NewPath
			if reverse {
				filePath = fp.OldPath
			}

			backupPath := filePath + backupSuffix
			fi, err := os.Stat(filePath)
			if err != nil {
				rollbackBackups(backups, logger)
				return "", errs.Wrap(errs.CodeStoreParseFailed, fmt.Sprintf("获取文件信息失败 %s", filePath), err)
			}
			origPerm := fi.Mode().Perm()

			data, err := os.ReadFile(filePath)
			if err != nil {
				// 回滚已创建的备份
				rollbackBackups(backups, logger)
				return "", errs.Wrap(errs.CodeStoreParseFailed, fmt.Sprintf("读取文件失败 %s", filePath), err)
			}

			if err := os.WriteFile(backupPath, data, origPerm); err != nil {
				rollbackBackups(backups, logger)
				return "", errs.Wrap(errs.CodeStoreWriteFailed, fmt.Sprintf("创建备份失败 %s", filePath), err)
			}

			backups[filePath] = backupPath
		}
	}

	// 步骤 3: 应用每个文件的补丁
	appliedFiles := []string{}
	for _, fp := range patch.Files {
		filePath := fp.NewPath
		if reverse {
			filePath = fp.OldPath
		}

		if err := applyFilePatch(filePath, &fp, reverse, logger); err != nil {
			// 回滚所有更改
			rollbackChanges(appliedFiles, backups, logger)
			return "", errs.Wrap(errs.CodeStoreWriteFailed, fmt.Sprintf("应用补丁失败 %s", filePath), err)
		}

		appliedFiles = append(appliedFiles, filePath)
	}

	// 步骤 4: 清理备份文件（成功后）
	if backup {
		for _, backupPath := range backups {
			// 保留备份文件，让用户手动删除
			logger.Info("已创建备份", zap.String("path", backupPath))
		}
	}

	action := "应用"
	if reverse {
		action = "反向应用"
	}

	var results []string
	for _, fp := range appliedFiles {
		results = append(results, fmt.Sprintf("✓ %s", fp))
	}

	// E4: 补丁应用成功后记录所有文件的 hash（用于后续外部修改检测）
	if globalFileTracker != nil {
		for _, fp := range appliedFiles {
			_ = globalFileTracker.Track(fp)
		}
	}

	summary := fmt.Sprintf("成功%s补丁（共 %d 个文件）:\n%s",
		action, len(appliedFiles), strings.Join(results, "\n"))

	if backup && len(backups) > 0 {
		summary += fmt.Sprintf("\n\n备份文件已创建（可手动删除）：")
		for _, bp := range backups {
			summary += fmt.Sprintf("\n  %s", bp)
		}
	}

	return summary, nil
}

// validateFilePatch 验证文件补丁是否可以应用（不实际修改文件）
func validateFilePatch(filePath string, fp *FilePatch, reverse bool) error {
	data, err := os.ReadFile(filePath)
	if err != nil {
		return errs.Wrap(errs.CodeStoreParseFailed, "读取文件失败", err)
	}

	lines := strings.Split(string(data), "\n")

	// 验证每个 hunk
	for _, hunk := range fp.Hunks {
		if err := hunk.Validate(); err != nil {
			return errs.Wrap(errs.CodeInvalidInput, "hunk 验证失败", err)
		}

		// 验证 hunk 是否匹配文件内容（使用无日志的 nop logger，仅做验证）
		if _, err := applyHunkToLines(lines, &hunk, reverse, true, zap.NewNop()); err != nil {
			return errs.Wrap(errs.CodeInvalidInput, "hunk 不匹配", err)
		}
	}

	return nil
}

// applyFilePatch 应用文件补丁
func applyFilePatch(filePath string, fp *FilePatch, reverse bool, logger *zap.Logger) error {
	// 读取原始文件信息以保留权限
	origInfo, err := os.Stat(filePath)
	if err != nil {
		return errs.Wrap(errs.CodeStoreParseFailed, "获取文件信息失败", err)
	}
	origPerm := origInfo.Mode().Perm()

	data, err := os.ReadFile(filePath)
	if err != nil {
		return errs.Wrap(errs.CodeStoreParseFailed, "读取文件失败", err)
	}

	lines := strings.Split(string(data), "\n")

	// 按顺序应用每个 hunk
	for _, hunk := range fp.Hunks {
		newLines, err := applyHunkToLines(lines, &hunk, reverse, false, logger)
		if err != nil {
			return errs.Wrap(errs.CodeStoreWriteFailed, "应用 hunk 失败", err)
		}
		lines = newLines
	}

	// 写回文件，使用原始文件权限
	newContent := strings.Join(lines, "\n")
	if err := os.WriteFile(filePath, []byte(newContent), origPerm); err != nil {
		return errs.Wrap(errs.CodeStoreWriteFailed, "写入文件失败", err)
	}

	// 验证写入后的文件权限是否正确
	newInfo, err := os.Stat(filePath)
	if err != nil {
		return errs.Wrap(errs.CodeStoreWriteFailed, "验证文件权限失败", err)
	}
	if newInfo.Mode().Perm() != origPerm {
		logger.Warn("文件权限与预期不一致",
			zap.String("file", filePath),
			zap.String("expected", fmt.Sprintf("%04o", origPerm)),
			zap.String("actual", fmt.Sprintf("%04o", newInfo.Mode().Perm())))
	}

	return nil
}

// applyHunkToLines 应用 hunk 到行数组，使用渐进匹配策略
func applyHunkToLines(lines []string, hunk *Hunk, reverse bool, validateOnly bool, logger *zap.Logger) ([]string, error) {
	// 使用模糊匹配查找 hunk 在文件中的位置
	matchResult, err := fuzzyMatchHunk(lines, hunk, reverse, logger)
	if err != nil {
		return nil, err
	}

	startLine := matchResult.StartLine

	if validateOnly {
		return lines, nil
	}

	// 应用修改
	result := []string{}
	result = append(result, lines[:startLine]...) // 保留前面的行

	filePos := startLine
	for _, line := range hunk.Lines {
		lineType := line.Type
		if reverse {
			if lineType == LineAdded {
				lineType = LineRemoved
			} else if lineType == LineRemoved {
				lineType = LineAdded
			}
		}

		switch lineType {
		case LineContext:
			if filePos >= len(lines) {
				return nil, fmt.Errorf("hunk 应用越界: filePos=%d 超出文件行数=%d", filePos, len(lines))
			}
			// 使用文件中的原始行（保留原始缩进）
			result = append(result, lines[filePos])
			filePos++
		case LineAdded:
			result = append(result, line.Content)
		case LineRemoved:
			if filePos >= len(lines) {
				return nil, fmt.Errorf("hunk 删除行越界: filePos=%d 超出文件行数=%d", filePos, len(lines))
			}
			filePos++ // 跳过删除的行
		}
	}

	// 添加后续的行
	if filePos > len(lines) {
		filePos = len(lines)
	}
	result = append(result, lines[filePos:]...)

	return result, nil
}

// rollbackBackups 回滚备份文件
func rollbackBackups(backups map[string]string, logger *zap.Logger) {
	for _, backupPath := range backups {
		if err := os.Remove(backupPath); err != nil {
			logger.Warn("删除备份文件失败", zap.String("path", backupPath), zap.Error(err))
		}
	}
}

// rollbackChanges 回滚所有更改
func rollbackChanges(appliedFiles []string, backups map[string]string, logger *zap.Logger) {
	for _, filePath := range appliedFiles {
		backupPath, ok := backups[filePath]
		if !ok {
			logger.Error("回滚失败：找不到备份文件", zap.String("file", filePath))
			continue
		}

		backupInfo, err := os.Stat(backupPath)
		if err != nil {
			logger.Error("回滚失败：获取备份文件信息失败",
				zap.String("file", filePath),
				zap.String("backup", backupPath),
				zap.Error(err))
			continue
		}

		data, err := os.ReadFile(backupPath)
		if err != nil {
			logger.Error("回滚失败：读取备份文件失败",
				zap.String("file", filePath),
				zap.String("backup", backupPath),
				zap.Error(err))
			continue
		}

		if err := os.WriteFile(filePath, data, backupInfo.Mode().Perm()); err != nil {
			logger.Error("回滚失败：恢复文件失败",
				zap.String("file", filePath),
				zap.Error(err))
			continue
		}

		logger.Info("已回滚", zap.String("file", filePath))
	}

	// 清理备份文件
	rollbackBackups(backups, logger)
}
